### ISSUE TITLE
Getting TypeError: Cannot read properties of undefined (reading 'ReactCurrentDispatcher') when using with Next15 / React19

### ISSUE THREAD

**Issue by alec-watts** [Nicolapps/mapkit-react#71] opened 2024-11-07 04:47 UTC

**Comment by lmammino** [comment] 2024-11-11 11:25
👍🏽 on this, experiencing a similar problem with Next.js 15. I have tried with both React 18 and 19.

**Comment by adminy** [comment] 2024-11-11 11:33
This seems to be related to vite as when bundling it in a next project using webpack this issue goes away.

**Comment by KlotzJesse** [comment] 2024-11-21 16:33
@adminy Yeah, can be fixed if mapkit-react add a option to vite.config to not bundle react like
`external: ["react", /^react\/.*/, "react-dom", /react-dom\/.*/],`

**Comment by alec-watts** [comment] 2024-11-26 17:22
Great thanks y'all. I copied the entire project into my Next App and have it working but would love to move back to using the package. Any change @KlotzJesse solution works ^? @adminy @lmammino @Nicolapps

**Comment by adminy** [comment] 2024-11-27 09:25
The problem is in the build process (vite bundling), no fix has been proposed yet. Depends on how you're using the map lib, but if its just a location pointing kind of application, the shortcut would be to just import mapkit.js directly and using a ref bypass react with perhaps a useEffect for the callback code.

**Comment by alec-watts** [comment] 2024-11-27 23:01
Thank you!!

**Comment by carwbrown** [comment] 2024-12-05 20:14
Downgrading to Next's version `14.2.20` solved the issue for me.

**Comment by nikischin** [comment] 2024-12-08 12:07
Could you test if #74 would be a possible fix for you? :)

**Closed** 2024-12-09 10:54 UTC

**Comment by Nicolapps** [comment] 2024-12-09 12:56
Hello everyone! I just release mapkit-react 1.15.3 which resolves this issue. I tested the new version on both Next.js 15 (with React 19) and Vite + React 19 (as well as Next.js 14 with React 18 and Vite + React 18) and it looks like the issue is resolved.
