### ISSUE TITLE
React 19: TypeError: undefined is not an object (evaluating 'h.ReactCurrentDispatcher')

### ISSUE THREAD

**Issue by nikischin** [Nicolapps/mapkit-react#73] opened 2024-12-07 17:26 UTC
I tried MapKit React with the official React 19.0.0 release. However, I get an MapKit React JS error:

```
TypeError: undefined is not an object (evaluating 'h.ReactCurrentDispatcher')
```

<img width="380" alt="image" src="https://github.com/user-attachments/assets/218250c0-48ea-4e4b-ba21-25fdfb000829">

**Comment by nikischin** [comment] 2024-12-07 18:04
Interesting I cannot reproduce in storybook, but in a clean create-vite-app it is easy to reproduce.

**Comment by nikischin** [comment] 2024-12-08 12:06
Ah actually this seems to be a possible duplicate of #71

**Comment by Nicolapps** [comment] 2024-12-09 12:49
Closing this issue as a duplicate of #91, thanks for reporting!

**Closed by Nicolapps** 2024-12-09 12:49 UTC
